### ISSUE TITLE
How to Configure the few tabs to be non-movable

### ISSUE THREAD

**Issue by pavan6014** [golden-layout/golden-layout-ng-app#11]
Is there any way we can make few tabs non-movable ?

**Comment by pbklink** [comment]
Hi @pavan6014,
This repository exists to demonstrate how to use Golden Layout in Angular.  It is not generally monitored for Golden Layout questions.  Best to ask Golden Layout questions at:
[https://github.com/golden-layout/golden-layout/issues](https://github.com/golden-layout/golden-layout/issues)
