### ISSUE TITLE
how to Allow the tab to movable only to certain dock sections not all dock sections

### ISSUE THREAD

**Issue by pavan6014** [golden-layout/golden-layout-ng-app#12]
Is there any way we can allow the tab to movable only to certain dock sections not all dock sections ?

**Comment by pbklink** [comment]
Hi @pavan6014,
This repository exists to demonstrate how to use Golden Layout in Angular.  It is not generally monitored for Golden Layout questions.  Best to ask Golden Layout questions at:
[https://github.com/golden-layout/golden-layout/issues](https://github.com/golden-layout/golden-layout/issues)
