### ISSUE TITLE
How to add dynamic CSS based on configuration

### ISSUE THREAD

**Issue by pavan6014** [golden-layout/golden-layout-ng-app#13]
Is there any way we can apply CSS to stacks based on JSON configuration ?

**Comment by pbklink** [comment]
Hi @pavan6014,
This repository exists to demonstrate how to use Golden Layout in Angular.  It is not generally monitored for Golden Layout questions.  Best to ask Golden Layout questions at:
[https://github.com/golden-layout/golden-layout/issues](https://github.com/golden-layout/golden-layout/issues)
