### ISSUE TITLE
Issue in a Production Enviroment

### ISSUE THREAD

**Issue by Aloterraner** [golden-layout/golden-layout-ng-app#14]
Hello, 

First of all, thank you all very much for maintaining this project. It is a great package. 

Now for the issue. While the app demo in its current state works as intended in an angular development environment when creating an angular production build, minifying and uglifying the code destroys the ComponentRegistration logic used, as the component constructor function names will be all uglified to the same name. This obviously breaks the map used with string keys. 

To solve this, there are probably many avenues, for example, the easiest would be using static string names instead of constructor.name, as these aren't compressed, which however has its own issues, as we would need to maintain it across all references and thus multiple files. Alternatively registering the function names to not be minified could be another option. 

While answering the latter question perfectly might not be in the scope of this demo, fixing the issue and shining a light on this trap fall could help users, which study this example to learn the usage of the package with Angular. 

Greetings, 
Michael Martini

**Comment by pbklink** [comment]
Thanks @Aloterraner - Have fixed with static string names. :smiley:
