### ISSUE TITLE
Component id setter

### ISSUE THREAD

**Issue by unusorin** [golden-layout/golden-layout-ng-app#7]
Just a simple question: how do you set the component id in the context of goldenLayout.newComponent? I've searched quite a bit for this aspect and I didn't find any info, just the getter which returns an empty string.

**Comment by pbklink** [comment]
Use LayoutManager.newItem().  newComponent() is a simplified version of addItem().

**Comment by pbklink** [comment]
Best to ask GoldenLayout questions at [Golden Layout GitHub repository](https://github.com/golden-layout/golden-layout)

**Comment by unusorin** [comment]
Thank you! I've noticed that method, and I will take a look into it a bit better. On a first glance I though it's only for adding containers/groups.
