### ISSUE TITLE
NgxGoldenLayout2?

### ISSUE THREAD

**Issue by fresto32** [golden-layout/golden-layout-ng-app#8]
Hi Paul,

Firstly, thank you very much for maintaining `golden-layout` and for providing us this source code for reading. It's a huge help to my team.

My organisation has been heavily relying on `ngx-golden-layout` in our frontend. Since that package has not been well maintained, I used this repository to sort of "recreate" `ngx-golden-layout`. I was wondering whether you would consider looking at it considering that it heavily borrows from this codebase.

https://github.com/fresto32/ngx-golden-layout-2/tree/main
https://www.npmjs.com/package/ngx-golden-layout-2

I was wondering whether you might consider porting the code across as another repository under `golden-layout` or whether this code could be of use to you or anyone else in the organisation. 

In any case, if there's anything I can do to help, please let me know.

Thanks,

Taj

p.s. Happy to fork into this library / any alternative you think appropriate

**Comment by pbklink** [comment]
Hi Taj,

I also previously used ngx-golden-layout however only to get basic access to Golden Layout.  I never looked into its full capabilities.  Once version 2 came out, I no longer needed to use ngx-golden-layout.

Could you please briefly describe the features ngx-golden-layout-2 has, that are not included in Golden Layout 2.

Note that @martin31821 is the original author of ngx-golden-layout and also the maintainer of the golden-layout repository and organisation. He should be involved in this conversation as well.

**Comment by martin31821** [comment]
Hi Taj,

that's correct that ngx-golden-layout hasn't got much attention recently. I do plan to upgrade it to version 2 mid-term, but that needs to be

**Comment by fresto32** [comment]
Hi Martin and Paul,

Thanks for replying to the thread and maintaining golden-layout. All my colleagues agree that there isn't anything quite like Golden Layout and it suits our use case perfectly.

> Could you please briefly describe the features ngx-golden-layout-2 has, that are not included in Golden Layout 2.

The issue my organisation has with using Golden Layout 2 directly, as per the examples in this repository, is the amount of "layout" specific code that needs to be added to Angular to get the basic features of Golden Layout 2. The original `ngx-golden-layout` module allowed us to abstract away a lot of these details, which is the goal of `ngx-golden-layout-2`. 

- The host component is abstracted away
- The host component service is hidden from users
- The user can still access golden layout via GoldenLayoutManager.goldenLayout

In the end, `ngx-golden-layout-2` allows someone, who doesn't really need to know much about Golden Layout, to get it going.

Btw, if you check out the github repo and run the demo application, you'll see it retains all the features of this repository, while abstracting most of the implementation details in `NgxGoldenLayout2`.

Thanks for taking the time to think about this with me. Please let me know any way I can help out.
